// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    // `.expo` holds generated route types, regenerated by the bundler.
    ignores: ['dist/*', 'android/*', 'ios/*', '.expo/*'],
  },
  {
    // Tests re-`require()` modules on purpose: the playback service is a
    // singleton, so each case pairs `jest.resetModules()` with a fresh require
    // to get isolated state. A static import would defeat that.
    files: ['**/__tests__/**/*.ts', '**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
]);
